version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    # build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    depends_on:
      - frontend
      - node
      - webrtc
  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=<your_email>
  frontend:
    container_name: frontend
    build: "./frontend"
    expose:
      - 80
    depends_on:
      - node
      - webrtc
    links:
      - node
      - webrtc
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - ./init/postgres/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./init/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - PGUSER=${PGUSER}
      - PGDATA=${PGDATA}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5435:5432"
    healthcheck:
      # test: pg_isready -U postgres
      test: ["CMD", "pg_isready", "-q"]
  node:
    container_name: node
    build: "./backend/node"
    depends_on:
      - db
    links:
      - db
    expose:
      - 5001
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
  webrtc:
    container_name: webrtc
    build: "./backend/webrtc"
    expose:
      - 8080
volumes:
  dbdata:
